PR : 공용 Button작성
keeprok/First-project pull request #8
Opened 2024-05-14 16:01 UTC by keeprok

## 🔥 Issues

- close #7 

<br/>
<br/>

## 🎯 작업 내용

[common-Button 생성](https://github.com/keeprok/First-project/commit/79b81166f1bb44c915e36355ae621f97bd4ad4ae)
- 기본적으로 사용될 shape , color을 cva를 통해서 2가지씩만 작성하였습니다
    -  추후 publish 를 통해서 전체적으로 나중에 명환한 디자인을 잡을예정입니다 
- shape는 현재 shape : { rectangular: 'rounded-none', roundSqure :'rounded-lg'}  , color또한 : {blue,red} 두가지 만있고 default는 rectangular , red로 되있습니다
<br/> 

 [Feat : 기존 사이즈를 min으로 돌렸습니다](https://github.com/keeprok/Firstproject/commit/0c5d97af00425c31993831d83b0b0f9e7354324a)
- 사진과같이 최소 사이즈 w-48 그리고 fit으로 변경했습니다
<img width="954" alt="스크린샷 2024-05-15 오전 12 57 52" src="https://github.com/keeprok/First-project/assets/140785214/c0f24e7e-bb46-453c-8fee-86a745c90a00">

<br/>
<br/>

<br/>
<br/>

-----

#### 🙏 꼭 리뷰 남겨주세요.!!
- 아래 양식에 맞게 리뷰 부탁드립니다..!!
- 수정을 요구하는 게 아니라면, "Description" 을 꼭 남기지 않아도 좋습니다. 👍

```text
# Request Level

# Description

```

2024-05-14 17:58 UTC, snkchan reviewed
- pr은 제가 이런이런 작업들을 했습니다. 확인후 이상이없다면 저희프로젝트에 포함시켜도될까요? 의 의미가있다고 생각합니다.
- 지금 올려주신 pr은  `이런이런 작업들을 했습니다` 를 확인하기좀 힘들어요. 이렇게 올려주신다면 아마 리뷰하는사람들이 제대로 중요한부분을 캐치 못할 수 도 있겟죠??
지금보면 button생성했습니다. 커밋에가보니 변경한 파일들이 너무많아서 어디서 버튼을 작업했다는거지? 라는생각이듭니다. 해당커밋에 tailwindcss포함한것 pr템플릿올린거 이런게포함되있어서 앞으로 작업단위 로 커밋해주시고 해당내용에대해 설명해주시면 좋을것같아요.

2024-05-14 17:58 UTC, snkchan commented on src/common/button/index.tsx
> +const ButtonVariants = cva(` w-fit min-w-48 h-48  text-center px-[1rem] py-[0.5rem] text-white `, {
- min-w-48인 이유가있을까요??? 48이 적은사이즈는 아닌데 프로젝트의 모든버튼이 48이상이여야하는 기준이 있는지 궁굼합니다.
- h-48로 설정해주셨는데 이것도 어떤 이유가있는사이즈 인가요?? cva를 사용중이신데 넓이나 높이에대한 것들도 cva에 variants로 관리하는 방식은 어떨까요? 
- 혹은 넓이 높이를 관계없이쓸수있게 w-fit h-fit 후에 padding값을이용해서 사이즈를 조정해보는 방법도 있을것 같습니다.

2024-05-14 17:58 UTC, snkchan commented on src/pages/home/index.tsx
> +        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
- pr을올리실땐 이런예시코드는 지워주시고 올려주셔야할거 같아요. 후에 변경점이또잡히는 문제점이 있을 수 있고 이렇게 예시코드가 남아있다면 리뷰에 어려움이 있을수 있을것 같아요.
- 해당변경점은 지금버튼 이미지를 첨부하기위해 pr에포함된것 같은데 pr에변경점이 하나생길때마다 리뷰하는사람들은 볼곳이 많아집니다. 이런 예시코드는 이미를 사진을찍은후 코드는 지우고 올려주시면 좋을 것 같아요.

2024-05-14 17:58 UTC, snkchan commented on src/common/button/index.tsx
> +  };
- 정의하신부분은 코드상 문제는 없겠지만 컴포넌트의 기본 props를 사용하기위해 
```React.ButtonHTMLAttributes<HTMLButtonElement>```를 사용하셧느데 조금더 좋은 방법이 있을 수 있을것 같아요 [여기](https://velog.io/@jihyeong00/TS-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8%EB%A5%BC-%EB%A7%8C%EB%93%A4%EA%B8%B0-%EC%9C%84%ED%95%B4-%EC%99%84%EB%B2%BD%ED%95%9C-%ED%83%80%EC%9E%85%EC%9D%84-%EC%A3%BC%EB%8A%94-%EB%B0%A9%EB%B2%95) 서 ComponentProps 라는 부분도 한번 참고해보시면 좋은내용일것 같아요.

2024-05-14 18:01 UTC, TransparentDeveloper requested changes
고생하셨습니다. 👍

가장 먼저 중요한 한가지를 말씀드리자면,,

<div align="center">

<img width="295" alt="스크린샷 2024-05-15 오전 2 59 07" src="https://github.com/keeprok/First-project/assets/50646145/a17e0e36-5a9c-4937-b658-dd19a3cce6d5">

</div>

커밋메시지 컨벤션을 지켜주셔야합니다.
같이 했던 프로젝트의 것 말고, 개인적으로 설정한 컨벤션이 있나요?

2024-05-14 18:01 UTC, TransparentDeveloper commented on .github/pull_request_template.md
> +```
- 작업 내용를 분명히 해서, commit을 하고 PR 을 열어주시는 게 좋습니다.
- pull request template 은 #7  이슈와도 상관이 없고, pr 제목과 본문 어디에서도 관련 내용이 작성되어 있지 않습니다.
- issue 발행할 때 목표를 명확히 하고, 그것과 관련된 작업 결과만을 pr 에 반영해주세요.

2024-05-14 18:01 UTC, TransparentDeveloper commented on src/common/button/index.tsx
> +  };
- 이 타입은 왜 이곳에 선언되어 있나요??
- `src > types` 아래에 타입관리 폴더도 있는 것 같은데,,
  - `ButtonProps` 는 types 폴더에서 선언되었네요..
- 각 폴더, 파일 별로 관리하는 대상의 기준을 알려주실수 있나요?

2024-05-14 18:01 UTC, TransparentDeveloper commented on src/pages/home/index.tsx
> +      <Button color="blue" shape="roundSqure">
```ts
    <Button shape="roundSqure">3</Button>
    <Button>3</Button> // 👈,👆 똑같다..
```

- 기본값 설정이 되어있어서, 불필요한 속성을 전달한 것 같습니다.

2024-05-14 18:19 UTC, keeprok commented on src/pages/home/index.tsx
> +      <Button color="blue" shape="roundSqure">
둘이 다른 모양입니다...  Button. 의 default는 rectangular 입니다

2024-05-15 00:55 UTC, TransparentDeveloper commented on src/pages/home/index.tsx
> +      <Button color="blue" shape="roundSqure">
아잇 죄송;;;;;

2024-05-15 08:22 UTC, keeprok commented on src/common/button/index.tsx
> +  };
type에 관해서 조금 정의를 다시생각하고있습니다 type폴더가 있긴한데 type폴더 를 재사용하는 부분들을 폴더에 담는것이 더좋은것인지 아니면 type폴더안에서 세분화해서 나누는것이 좋은것인지 생각하고있습니다 
- 각폴더의 정의는 어제 말로 말씀드려서 작성은 안하겠습니다

2024-05-17 15:27 UTC, keeprok commented on src/pages/home/index.tsx
> +        4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
좋은 조언 감사합니다 혼자하는 프로젝트라 생각하니 안일했던거같습니다

2024-05-17 15:28 UTC, keeprok commented on .github/pull_request_template.md
> +```
넵 앞으로 조심하도록 하겠습니다 초기이닛과정에서 분명히 다설정해야되는부분이였는데 나중에라 도 깨달았을때 나눠서 넣는것이 더좋았던거 같습니다

2024-05-17 15:32 UTC, keeprok commented on src/common/button/index.tsx
> +  };
[fix : pr 리뷰에 맞춰 수정하였습니다](https://github.com/keeprok/First-project/pull/8/commits/5e8b9ad29c918cb88142a81060ef036d44aeecb6) type 위치를  variants 와 common으로 types에 묶어서 넣엇는데 사실 파일위치에 관한건 아직도 고민중이라 후에 다시 정리할예정입니다

2024-05-17 15:33 UTC, keeprok commented on src/common/button/index.tsx
> +const ButtonVariants = cva(` w-fit min-w-48 h-48  text-center px-[1rem] py-[0.5rem] text-white `, {
[fix : pr 리뷰에 맞춰 수정하였습니다](https://github.com/keeprok/First-project/pull/8/commits/5e8b9ad29c918cb88142a81060ef036d44aeecb6) 수정하엿습니다 제시 해주신의견이 훨씬 맞는거같습니다 처음 의견을 받앗을때 똑같이 만들어서 주제와 다른 부분으로 만들어진것같습니다

2024-05-17 15:34 UTC, keeprok commented on src/common/button/index.tsx
> +  };
이부분은 조금더 참고하고 수정조치를 type들을 묶어서 한번더 pr을 열도록 하겠습니다

2024-05-17 15:40 UTC, keeprok commented
추가적으로 저스스로 에게 reivew를 달자면 수정에서도 commit을 수정사항에맞춰 하나하나 따로 올려야 rievew를 올린사람이 보기 가 편합니다 그리고 같은것을 게속 안보게 될거같네요 이부분도 기억하기 위해 적어두겠습니다

2024-05-18 02:49 UTC, TransparentDeveloper requested changes
고생하셨습니다.!

2024-05-18 02:49 UTC, TransparentDeveloper commented on src/common/button/index.tsx
> +import { ButtonVariants } from '../../types/variants';
저도 자주 까먹긴하는데,, 계속 신경써야합니다. 
`import type`

2024-05-18 02:49 UTC, TransparentDeveloper commented on src/common/button/index.tsx
> +      {children}
출력이 같아도 꼭 필요한 코드만 작성해야 합니다.! 
`cn()` 이 꼭 필요할까요?
해당 함수의 기능이 무엇인지 알려주실 수 있나요??

2024-05-18 02:58 UTC, TransparentDeveloper commented
리엘님만의 기준이 따로 있다면 모르겠지만, 보통 "fix" 는 버그 수정시 사용되는 컨벤션인 것 같습니다.
"feat", "fix", "refactor" 등 은 커밋메시지에 자주 사용되는 것 같은데, 기준을 맞춰 보는 게 좋을 것 같아요.!

참고로 chaeg-check 에서도 'fix' 는 "에러" 를 해결한 커밋에 대해 남겼습니다.!

<img width="279" alt="" src="https://github.com/keeprok/First-project/assets/50646145/3dfe1bbe-83de-44e1-94aa-65f75d767c55">

2024-05-18 05:47 UTC, keeprok commented
흠 refactor더 좋았을거같네요  혼자 하더라도 컨벤션을 만들어서 해보도록하겠습니다

2024-05-18 05:57 UTC, keeprok commented on src/common/button/index.tsx
> +import { ButtonVariants } from '../../types/variants';
[refactor : import 시 type 같이 선언](https://github.com/keeprok/First-project/pull/8/commits/b59b107eaee149a7451cb2b17f4b828461f8278b) 선언햇습니다 감사합니다

2024-05-18 07:48 UTC, keeprok commented on src/common/button/index.tsx
> +import { ButtonVariants } from '../../types/variants';
[refactor : import 시 type 같이 선언](https://github.com/keeprok/First-project/pull/8/commits/b59b107eaee149a7451cb2b17f4b828461f8278b) 수정했습니다 앞으로 조금더 자세히 봐야겠군요

2024-05-18 07:52 UTC, keeprok reviewed
다들 봐 주셔서 감사합니다

2024-05-18 07:52 UTC, keeprok commented on src/common/button/index.tsx
> +      {children}
<img width="690" alt="스크린샷 2024-05-18 오후 4 51 20" src="https://github.com/keeprok/First-project/assets/140785214/8ae0f339-2f3c-494c-8a25-a82f1082bd00">
<img width="94" alt="스크린샷 2024-05-18 오후 4 51 10" src="https://github.com/keeprok/First-project/assets/140785214/d3a7465d-fb5b-4428-8848-71c601513512">
없어도 잘되는걸보고 필요 없던 코드를 넣은것같네요 앞으로 하나씩넣어보고 하겠습니다 새로운 개념이라 평소 하던데로 못했네요

2024-05-18 08:00 UTC, merged